// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
	'后台管理系统': 'Background Management System',
	"后台统计": "Background Statistics",
	"用户统计": "User Statistics",
	"用户": "User",
	"用户ID": "User ID",
	"用户名": "User Name",
	"查询": "Search",
	"用户头像": "User Profile",
	"创建时间": "Creation Time",
	"最后一次登录时间": "Last Login Time",
	"拥有摄像机数量": "Number of Cameras Owned",
	"摄像机设备ID": "Camera Equipment ID",
	"设备分享统计": "Equipment Sharing Statistics",
	"用户设备对应关系": "Correspondence between User and Equipment",
	"设备ID": "Device ID",
	"属主用户名": "Belongs to the User Name",
	"属主用户ID": "User ID",
	"属主ID": "User ID",
	"云类型": "Cloud Service Type",
	"绑定时间": "Binding Time",
	"摄像机名": "Camera Name",
	"授权人数": "Number of Authorized Persons",
	"是否公开": "Whether to Open",
	"是否公共": "Whether to Open",
	"是否允许评论": "Comment Authority",
	"操作": "Operation",
	"设备状态统计": "Equipment Status Statistics",
	"设备状态": "Device Status",
	"设备信息": "Equipment Information",
	"硬件型号": "Hardware Model",
	"固件版本": "Firmware Version",
	"最近一次升级状态": "Recent Upgrade Status",
	"在线状态": "Online State",
	"首次上线时间": "First Online Time",
	"开始时间": "Start Time",
	"截止时间": "End Time",
	"结束时间": "End Time",
	"平台": "Platform",
	"最近一次固件更新时间": "Latest Firmware Update Time",
	"最近一次上线时间": "Last Online Time",
	"当前在线状态": "Current Online Status",
	"IP地理位置": "IP",
	"数据统计": "Data Statistics",
	"今天": "Today",
	"最近7天": "Last 7 Days",
	"最近30天": "Last 30 Days",
	"时间段": "Period of Time",
	"总计新增用户数（个）": "Total Number of New Users",
	"新增微信授权用户（个）": "WeChat Authorized New Users",
	"新增普通用户数（个）": "Number of New Common Users",
	"新增正常用户数（个）": "Number of New Common Users",
	"新增设备数（个）": "Number of New Equipment",
	"新增国内设备数（个）": "Number of New Domestic Equipment",
	"新增国外设备数（个）": "Number of New Foreign Equipment",
	"羚羊云": "Antelope Cloud",
	"云": "Cloud",
	"云服务": "Cloud service",
	"云平台": "Cloud platforms",
	"羚羊（个）": "Antelope ",
	"羚羊": "Antelope ",
	"百度云": "Baidu Cloud",
	"百度（个）": "Baidu ",
	"百度": "Baidu ",
	"总数（个）": "Total",
	"设备在线统计": "Current Online Devices",
	"在线": "Online",
	"离线": "Offline",
	"设备总数：": "Total Number of Devices：",
	"设备分布统计": "Equipment Distribution Statistics",
	"设备总数": "Total Number of Devices",
	"设备数": "Number of Devices",
	"国内": "Domestic",
	"国外": "Foreign",
	"黑龙江": "Heilongjiang",
	"陕西": "Shanxi",
	"重庆": "Chongqing",
	"辽宁": "Liangning",
	"福建": "Fujian",
	"湖南": "Hunan",
	"湖北": "Hubei",
	"浙江": "Zhejiang",
	"河南": "Henan",
	"河北": "Hebei",
	"江西": "Jiangxi",
	"江苏": "Jiangsu",
	"新疆": "Xinjiang",
	"广西": "Guangxi",
	"广东": "Guangdong",
	"山西": "Shanxi",
	"山东": "Shandong",
	"安徽": "Anhui",
	"宁夏": "Ningxia",
	"天津": "Tianjin",
	"四川": "Sichuan",
	"吉林": "Jilin",
	"台湾": "Taiwan",
	"北京": "Beijing",
	"内蒙古": "Neimenggu",
	"云南": "Yunnan",
	"上海": "Shanghai",
	"海南": "Hainan",
	"青海": "Qinghai",
	"贵州": "Guizhou",
	"香港": "Xianggang",
	"西藏": "Xizang",
	"甘肃": "Gansu",
	"澳门": "Aomen",
	"其他": "Others",
	"羚羊云数据统计": "Antelope Cloud Data Statistics",
	"设备统计": "：Equipment Statistics",
	"活跃设备统计": "Active Device Statistics",
	"活跃设备推流统计": "Active Device Push Traffic Statistics",
	"观看人数": "The Number of People Watching",
	"流量统计": "Flow Statistics",
	"上传流量统计": "Upload Traffic Statistics",
	"下载流量统计": "Download Traffic Statistics",
	"5分钟统计": "5 Minute Statistics",
	"日统计": "Daily Statistics",
	"单位:GB": "Unit: GB",
	"时间": "Time",
	"带宽统计": "Bandwidth Statistics",
	"上传带宽统计": "Upload Bandwidth Statistics",
	"下载带宽统计": "：Download Bandwidth Statistics",
	"存储统计": "Event Storage Statistics",
	"事件存储统计": "Download Traffic Statistics",
	"单位:小时": "Unit: Hour",
	"7天循环存储总时长统计": "Total Time Statistics of 7 Day Cycle",
	"30天循环存储总时长统计": "Total Time Statistics of 30 Day Cycle",
	"单位：秒": "Unit: Second",
	"设备查询": "Device Query",
	"已上线": "on line",
	"台": " ",
	"设备数（台）": "Number of Devices ",
	"城市": "City",
	"区域占比": "Area proportion",
	"最近一次登录时间": "Last login time",
	"首次上线结束时间": "The end time of the first line",
	"首次上线开始时间": "First on-line start time",
	"暂无记录": "No record",
	"设备数据": "Device Data",
	"绑定设备": "Bound Devices",
	"请选择硬件型号": "Select Device Model",
	"请选择固件版本": "Select F/W Version",
	"请选择云服务": "Select Cloud Service",
	"当前云服务类型": "Current Cloud Service",
	"到期时间": "Due Time",
	"请选择最后一次升级状态": "Last Time Updated Status",
	"当前固件版本": "Current F/W Version",
	"设备最近一次固件更新时间": "Last F/W Updated Time",
	"最新一次升级状态": "Update Status",
	"分享状态": "Sharing Status",
	"设备管理": "Devices Management",
	"评论审核": "Comment Moderation",
	"评论内容": "Comment Content",
	"IP地址": "IP",
	"全选": "Select All",
	"用户昵称": "Nickname",
	"评论": "Comment",
	"评论时间": "Comment Time",
	"推荐活动": "",
	"摄像机列表": "Camera List",
	"名称": "Name",
	"推荐列表": "Recoomend List",
	"保存": "Save",
	"黑名单": "Blocked List",
	"设备名称": "Device Name",
	"请选择拉黑状态": "Shield Status ",
	"清空": "empty",
	"未拉黑":"Unblock",
	"已拉黑": "Blocked",
	"所属渠道": "Channel",
	"举报数": "Report Number",
	"最新举报时间": "Last Report Time",
	"处理原因": "Process Reason",
	"操作用户名": "Process By",
	"状态": "Status",
	"拉黑": "Block",
	"详细": "Details",
	"删除": "Delete",
	"意见反馈": "Feedback",
	"用户反馈": "Customer Feedback",
	"联系方式": "Contact Information",
	"手机型号": "Phone Model",
	"APP版本": "APP Version",
	"创建日期": "Creation Date",
	"处理人": "Process By",
	"处理时间": "Process Time",
	"处理状态": "Process Status",
	"备注": "Remark",
	"处理": "Process",
	"第": " ",
	"条": " ",
	"共": "Total",
	"上一页": "Previous Page",
	"下一页": "Next Page",
	"到第": "To",
	"页": "Page",
	"确定": "OK"
};